# Generated by Django 4.1.5 on 2023-08-14 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='convertedImage/')),
                ('corner1_x', models.FloatField()),
                ('corner1_y', models.FloatField()),
                ('corner2_x', models.FloatField()),
                ('corner2_y', models.FloatField()),
                ('corner3_x', models.FloatField()),
                ('corner3_y', models.FloatField()),
                ('corner4_x', models.FloatField()),
                ('corner4_y', models.FloatField()),
                ('hfov', models.FloatField()),
                ('vfov', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploadedImages/')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('paintUsedGallons', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paintUsedLiters', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prevPaintUsedGallons', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prevPaintUsedLiters', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
