# Generated by Django 4.1.5 on 2023-07-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0004_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='paintUsedGallons',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='paintUsedLiters',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
